# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c015f408f821baccbe7f427ca5d46349fa97ef3e72d6a04c2e8c6e44ee36377bc8a244e4c9a3ac8218f3bea9ca1d1fd065709d4cd81b02935cd6cc6ba7fb2b3c

test:
  secret_key_base: 84dd5c23a216ce2e47b3e8569fb4d36a3a0d9059ff421b828bd63a7b46ecf70ce622f7f5058ed14c3ff1106c9d1d89c3b7483b765cdbf9b7f8913159c5fc6e4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
